name: 'Deploy'
on: [push]

jobs:
  deploy:
    name: 'Deploy to Neocities'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build
      - uses: kognise/neocities-deploy-action@v1
        with:
          neocities_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          directory: 'out/'
